"""add lazy

Revision ID: 006dcc66f4b2
Revises: b18ac2cc399a
Create Date: 2023-06-04 18:12:03.311651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '006dcc66f4b2'
down_revision = 'b18ac2cc399a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
