"""fix

Revision ID: 08726c2c37da
Revises: a41d1f714925
Create Date: 2023-06-04 16:22:00.116317

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08726c2c37da'
down_revision = 'a41d1f714925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('salaries_user_id_fkey', 'salaries', type_='foreignkey')
    op.create_foreign_key(None, 'salaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salaries', type_='foreignkey')
    op.create_foreign_key('salaries_user_id_fkey', 'salaries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
