"""fix

Revision ID: 30d7708f66d8
Revises: 08726c2c37da
Create Date: 2023-06-04 16:25:43.097427

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30d7708f66d8'
down_revision = '08726c2c37da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
