"""add lazy

Revision ID: 846b47f7bb4f
Revises: 30d7708f66d8
Create Date: 2023-06-04 18:08:26.355784

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '846b47f7bb4f'
down_revision = '30d7708f66d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
