"""add created_date in Salary

Revision ID: a41d1f714925
Revises: 772d63897d4e
Create Date: 2023-06-04 14:47:01.949490

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a41d1f714925'
down_revision = '772d63897d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaries', 'created_date')
    # ### end Alembic commands ###
