"""add lazy

Revision ID: b18ac2cc399a
Revises: 846b47f7bb4f
Create Date: 2023-06-04 18:11:38.755324

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b18ac2cc399a'
down_revision = '846b47f7bb4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
