"""add lazy

Revision ID: f02e74700280
Revises: 006dcc66f4b2
Create Date: 2023-06-04 18:15:07.350627

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f02e74700280'
down_revision = '006dcc66f4b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
